# Generated by Django 3.1.7 on 2021-03-08 10:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fesbbook_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_code', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{100,999}$')])),
                ('study_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default=None, max_length=50, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, default='default_profile_image.png', null=True, upload_to='')),
                ('year_of_enrollment', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=fesbbook_app.models.current_year)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'M'), ('Ž', 'Ž')], default=None, max_length=1)),
                ('isActive', models.BooleanField(default=False)),
                ('study', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fesbbook_app.study')),
            ],
        ),
    ]
