# Generated by Django 3.1.7 on 2021-04-05 10:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fesbbook_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_code', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{100,999}$')])),
                ('study_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default=None, max_length=50, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('year_of_enrollment', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=fesbbook_app.models.current_year)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'M'), ('Ž', 'Ž')], default='M', max_length=1)),
                ('isActive', models.BooleanField(default=False)),
                ('lastActivity', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fesbbook_app.study')),
            ],
            options={
                'ordering': ['-isActive', '-lastActivity'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('message_file', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('message_file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('message_file_icon', models.CharField(blank=True, max_length=22, null=True)),
                ('chat_room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='fesbbook_app.chatroom')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='fesbbook_app.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='fesbbook_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='first_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_student', to='fesbbook_app.student'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='second_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_student', to='fesbbook_app.student'),
        ),
    ]
